version: "2"

services:
  tor:
    image: goldy/tor-hidden-service
    links:
      - paste
    environment:
        # Set mapping ports
        PASTE: 80:80
        # Set private key
        PASTE_KEY: |
            -----BEGIN RSA PRIVATE KEY-----
            Your Private Key Here!
            -----END RSA PRIVATE KEY-----

  paste:
    image: daknob/torpaste
    hostname: paste
    volumes_from:
      - data
  data:
    image: tianon/true
    volumes:
      - paste_data:/torpaste/pastes/
volumes:
  paste_data:
    driver: local
